trigger:
  branches:
    include:
    - main
  paths:
    include:
    - azure-pipelines.yaml

resources:
- repo: self

variables:
  IMAGE_NAME: houssemdocker/album-backend-api
  DOCKERHUB_REPOSITORY: jocasmen94/album-backend-api
  TAG: '$(Build.BuildNumber)'  # Use Build.BuildNumber as the tag
  CONTAINERAPPS_APP: album-backend-api
  CONTAINERAPPS_ENVIRONMENT: aca-environment
  RESOURCE_GROUP: rg-containerapps-azure-pipelines

stages:
- stage: BuildAndPush
  displayName: Build and Push Docker Image
  jobs:
  - job: BuildAndPushJob
    displayName: Build and Push
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/backend_api/backend_api_csharp/Dockerfile'
        repository: $(IMAGE_NAME)
        tags: $(TAG)

    - task: Docker@2
      displayName: Docker Login
      inputs:
        command: login
        containerRegistry: 'dockerhub-connection'

    - task: Docker@2
      displayName: Tag image
      inputs:
        command: tag
        arguments: '$(IMAGE_NAME):$(TAG) $(DOCKERHUB_REPOSITORY):$(TAG)'

    - task: Docker@2
      displayName: Push image to Docker Hub
      inputs:
        containerRegistry: 'dockerhub-connection'
        repository: $(DOCKERHUB_REPOSITORY)
        command: 'push'
        tags: '$(TAG)'

- stage: Deploy
  displayName: Deploy to Container Apps
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:

    - task: AzureContainerApps@1
      displayName: Deploy new container version
      inputs:
        azureSubscription: 'demo'
        imageToDeploy: '$(DOCKERHUB_REPOSITORY):$(TAG)'
        containerAppName: '$(CONTAINERAPPS_APP)'
        resourceGroup: '$(RESOURCE_GROUP)'
        containerAppEnvironment: '$(CONTAINERAPPS_ENVIRONMENT)'
        targetPort: '3500'
        ingress: 'external'
